import type { ActivityAction, Contract, ContractHistoryAction, ContractStats, Database, Payment, ScheduleItem } from './types';

export const STORAGE_KEY = 'aqsaty_local_v2';
export const PIN_KEY = 'aqsaty_pin_v2';
const DB_NAME = 'aqsaty_local_database';
const DB_STORE = 'state';
const PIN_HASH_KEY = 'aqsaty_pin_hash_v2';
const PIN_SALT_KEY = 'aqsaty_pin_salt_v2';
const uid = (prefix: string) => `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`;
export const createId = uid;
export const today = () => new Date().toISOString().slice(0, 10);
export const isValidDate = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(new Date(`${value}T00:00:00`).getTime());
export const isOverdue = (dueDate: string, referenceDate = today()) => dueDate <= referenceDate;
export const normalizePhone = (phone: string) => String(phone || '').replace(/[^0-9]/g, '').replace(/^00964/, '0').replace(/^964/, '0');
export const whatsappPhone = (phone: string) => { const normalized = normalizePhone(phone); return normalized.startsWith('0') ? `964${normalized.slice(1)}` : normalized; };
export const money = (amount: number) => `${Number(amount || 0).toLocaleString('ar-IQ')} د.ع`;
export const dateText = (date: string) => date ? new Date(`${date}T00:00:00`).toLocaleDateString('ar-IQ', { year: 'numeric', month: 'short', day: 'numeric' }) : '—';
export const whatsappTemplates = [
  { id: 'friendly', name: 'تذكير ودّي', body: 'السلام عليكم {name}،\n\nنذكّركم بلطف بقسطكم لدى {shop}.\nالمنتج: {product}\nالقسط رقم: {number} من {months}\nالاستحقاق: {date}\nالمتبقي: {amount}\n\nشكرًا لتعاونكم.' },
  { id: 'formal', name: 'إشعار رسمي', body: 'السيد/السيدة {name} المحترم/ة،\n\nنود إعلامكم بأن القسط رقم {number} من عقد {contract} مستحق بتاريخ {date}.\nالمبلغ المطلوب: {amount}\nالمنتج: {product}\n\nيرجى التسديد في الموعد المحدد. مع التقدير، {shop}.' },
  { id: 'short', name: 'رسالة مختصرة', body: 'مرحبًا {name}، قسطك لدى {shop} مستحق بتاريخ {date} بمبلغ {amount}. العقد: {contract} — القسط {number}/{months}. شكرًا.' },
  { id: 'followup', name: 'متابعة متأخرات', body: 'مرحبًا {name}،\n\nنود تذكيركم بوجود قسط يحتاج إلى متابعة لدى {shop}.\nالمنتج: {product}\nالعقد: {contract}\nالمبلغ المتبقي: {amount}\n\nنرجو التواصل معنا لإتمام التسديد أو ترتيب موعد مناسب.' },
  { id: 'appreciation', name: 'شكر وتأكيد', body: 'أهلًا {name}،\n\nشكرًا لالتزامكم مع {shop}. هذا تذكير بالقسط القادم رقم {number} من {months}.\nالمنتج: {product}\nالتاريخ: {date}\nالمبلغ: {amount}\n\nنسعد بخدمتكم دائمًا.' },
] as const;
export const emptyDatabase = (): Database => ({ customers: [], products: [], contracts: [], payments: [], activities: [], settings: { shopName: 'aqsaty', whatsappTemplate: 'السلام عليكم {name}،\n\nنذكّركم بقسطكم لدى {shop}:\nالمنتج: {product}\nرقم العقد: {contract}\nالقسط رقم: {number} من {months}\nتاريخ الاستحقاق: {date}\nالمبلغ المتبقي لهذا القسط: {amount}\n\nشكرًا لتعاونكم.', reminderTemplate: '' } });
export function loadDatabase(): Database { try { const raw = JSON.parse(localStorage.getItem(STORAGE_KEY) || '') as Partial<Database>; const base = emptyDatabase(); const products = (raw.products || []).map((entry) => { const product = { ...entry } as Database['products'][number]; return { ...product, stock: product.stock ?? 0, serialNumbers: product.serialNumbers ?? [], condition: product.condition ?? 'جديد', images: product.images ?? [], specs: product.specs ?? '', warranty: product.warranty ?? '' }; }); const contracts = (raw.contracts || []).map((entry) => { const contract = { ...entry } as Database['contracts'][number]; return { ...contract, status: contract.status ?? 'نشط', updatedAt: contract.updatedAt ?? contract.createdAt }; }); return { ...base, ...raw, activities: raw.activities || [], settings: { ...base.settings, ...(raw.settings || {}) }, products, contracts: contracts.map((contract) => ({ ...contract, history: contract.history || [] })) };  } catch { return emptyDatabase(); } }
export const ensureDatabase = loadDatabase;
function openLocalDatabase(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { if (!('indexedDB' in window)) return reject(new Error('IndexedDB غير مدعوم')); const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => request.result.createObjectStore(DB_STORE); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error || new Error('تعذر فتح التخزين المحلي')); }); }
export async function hydrateDatabase(): Promise<Database | null> { try { const db = await openLocalDatabase(); return await new Promise((resolve, reject) => { const request = db.transaction(DB_STORE, 'readonly').objectStore(DB_STORE).get('database'); request.onsuccess = () => resolve(request.result ? request.result as Database : null); request.onerror = () => reject(request.error); }); } catch { return null; } }
export const saveDatabase = (database: Database) => { const serialized = JSON.stringify(database); try { localStorage.setItem(STORAGE_KEY, serialized); } catch { /* IndexedDB is the durable store when the browser quota is full. */ } void (async () => { try { const db = await openLocalDatabase(); const transaction = db.transaction(DB_STORE, 'readwrite'); transaction.objectStore(DB_STORE).put(database, 'database'); } catch { /* Both stores can be unavailable in private/restricted browsing modes. */ } })(); };
export const getPin = () => localStorage.getItem(PIN_KEY) || '1234';
export const setPin = (pin: string) => localStorage.setItem(PIN_KEY, pin);
const encodeBytes = (value: Uint8Array) => btoa(String.fromCharCode(...value));
const decodeBytes = (value: string) => Uint8Array.from(atob(value), (character) => character.charCodeAt(0));
async function derivePin(pin: string, salt: Uint8Array) { const material = await crypto.subtle.importKey('raw', new TextEncoder().encode(pin), 'PBKDF2', false, ['deriveBits']); const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt: bufferOf(salt), iterations: 120000, hash: 'SHA-256' }, material, 256); return new Uint8Array(bits); }
export async function setSecurePin(pin: string) { const salt = crypto.getRandomValues(new Uint8Array(16)); const hash = await derivePin(pin, salt); localStorage.setItem(PIN_HASH_KEY, encodeBytes(hash)); localStorage.setItem(PIN_SALT_KEY, encodeBytes(salt)); localStorage.removeItem(PIN_KEY); }
export async function verifyPin(pin: string) { const storedHash = localStorage.getItem(PIN_HASH_KEY); const storedSalt = localStorage.getItem(PIN_SALT_KEY); if (!storedHash || !storedSalt) return pin === getPin(); const actual = await derivePin(pin, decodeBytes(storedSalt)); const expected = decodeBytes(storedHash); return actual.length === expected.length && actual.every((byte, index) => byte === expected[index]); }
export function logActivity(database: Database, action: ActivityAction, entity: string, entityId: string, description: string) { database.activities.unshift({ id: uid('activity'), action, entity, entityId, description, createdAt: new Date().toISOString() }); database.activities = database.activities.slice(0, 500); }
export function paidFor(database: Database, contract: Contract) { return database.payments.filter((p) => p.contractId === contract.id).reduce((sum, p) => sum + p.amount, 0); }
export function latePenaltyFor(item: ScheduleItem, referenceDate = today(), dailyRate = 0.001, maxRate = 0.25) { const remaining = Math.max(0, item.amount - item.paidAmount); const days = Math.max(0, Math.floor((new Date(`${referenceDate}T00:00:00`).getTime() - new Date(`${item.dueDate}T00:00:00`).getTime()) / 86400000)); return Math.min(remaining * maxRate, remaining * dailyRate * days); }
export function contractStats(database: Database, contract: Contract): ContractStats { const paid = paidFor(database, contract); const remaining = Math.max(0, contract.financedAmount - paid); const completed = contract.schedule.filter((s) => s.paidAmount >= s.amount).length; const overdue = contract.schedule.filter((s) => s.paidAmount < s.amount && isOverdue(s.dueDate)).length; const latePenalty = contract.schedule.reduce((sum, item) => sum + latePenaltyFor(item), 0); const nextDue = contract.schedule.find((s) => s.paidAmount < s.amount); return { paid, remaining, completed, overdue, latePenalty, percent: contract.financedAmount ? Math.min(100, paid / contract.financedAmount * 100) : 0, nextDue }; }
export function createSchedule(amount: number, months: number, startDate: string): ScheduleItem[] { if (!Number.isFinite(amount) || amount <= 0 || !Number.isInteger(months) || months <= 0 || !isValidDate(startDate)) throw new Error('بيانات جدول الأقساط غير صحيحة'); const base = Math.floor(amount / months); const remainder = amount - base * months; return Array.from({ length: months }, (_, i) => { const date = new Date(`${startDate}T00:00:00`); date.setMonth(date.getMonth() + i); return { id: uid('schedule'), number: i + 1, dueDate: date.toISOString().slice(0, 10), amount: base + (i === months - 1 ? remainder : 0), paidAmount: 0 }; }); }
export function customerByPhone(database: Database, phone: string) { const normalized = normalizePhone(phone); return database.customers.find((c) => normalizePhone(c.phone) === normalized); }
export function statusFor(item: ScheduleItem) { if (item.paidAmount >= item.amount) return { label: 'مدفوع', tone: 'paid' as const }; if (item.paidAmount > 0) return { label: 'جزئي', tone: 'partial' as const }; if (isOverdue(item.dueDate)) return { label: 'متأخر', tone: 'late' as const }; return { label: 'قادم', tone: 'due' as const }; }
function addHistory(contract: Contract, action: ContractHistoryAction, reason?: string) { contract.history = contract.history || []; contract.history.push({ id: uid('history'), action, at: new Date().toISOString(), reason }); }
export function addPayment(database: Database, contractId: string, scheduleId: string, payment: Omit<Payment, 'id' | 'contractId' | 'scheduleId' | 'receiptNumber'>) { const contract = database.contracts.find((c) => c.id === contractId); const schedule = contract?.schedule.find((s) => s.id === scheduleId); if (!contract || !schedule) throw new Error('القسط غير موجود'); const remaining = schedule.amount - schedule.paidAmount; if (payment.amount <= 0 || payment.amount > remaining) throw new Error('مبلغ الدفعة غير صحيح'); schedule.paidAmount += payment.amount; const receiptNumber = `REC-${new Date().getFullYear()}-${String(database.payments.length + 1).padStart(5, '0')}`; database.payments.push({ ...payment, id: uid('payment'), contractId, scheduleId, receiptNumber }); contract.updatedAt = new Date().toISOString(); if (contract.schedule.every((s) => s.paidAmount >= s.amount)) contract.status = 'مكتمل'; else if (contract.schedule.some((s) => s.paidAmount < s.amount && s.dueDate < today())) contract.status = 'متأخر'; addHistory(contract, 'دفعة'); logActivity(database, 'دفعة', 'payment', receiptNumber, `تسجيل دفعة ${money(payment.amount)} للعقد ${contract.number}`); }
export function updateContract(database: Database, contractId: string, changes: Pick<Contract, 'productName' | 'totalAmount' | 'downPayment' | 'months' | 'startDate' | 'status'>) { const contract = database.contracts.find((item) => item.id === contractId); if (!contract || !changes.productName.trim() || !Number.isFinite(changes.totalAmount) || changes.totalAmount <= 0 || !Number.isFinite(changes.downPayment) || changes.downPayment < 0 || changes.downPayment >= changes.totalAmount || !Number.isInteger(changes.months) || changes.months <= 0 || !isValidDate(changes.startDate)) throw new Error('بيانات العقد غير صحيحة'); const previous = contract.schedule; const nextSchedule = createSchedule(changes.totalAmount - changes.downPayment, changes.months, changes.startDate).map((item) => ({ ...item, paidAmount: Math.min(previous[item.number - 1]?.paidAmount || 0, item.amount) })); Object.assign(contract, { ...changes, financedAmount: changes.totalAmount - changes.downPayment, schedule: nextSchedule, updatedAt: new Date().toISOString() }); addHistory(contract, 'تعديل'); logActivity(database, 'تعديل', 'contract', contract.id, `تعديل العقد ${contract.number}`); }
export function deleteContract(database: Database, contractId: string) { const contract = database.contracts.find((item) => item.id === contractId); if (!contract) throw new Error('العقد غير موجود'); const product = database.products.find((item) => item.id === contract.productId); if (product) { product.stock += 1; if (contract.serialNumber && !product.serialNumbers.includes(contract.serialNumber)) product.serialNumbers.push(contract.serialNumber); } database.contracts = database.contracts.filter((item) => item.id !== contractId); database.payments = database.payments.filter((payment) => payment.contractId !== contractId); logActivity(database, 'حذف', 'contract', contractId, `حذف العقد ${contract.number} نهائيًا`); }
export function rescheduleItem(database: Database, contractId: string, scheduleId: string, dueDate: string, amount?: number) { const contract = database.contracts.find((c) => c.id === contractId); const item = contract?.schedule.find((s) => s.id === scheduleId); if (!contract || !item || !isValidDate(dueDate)) throw new Error('بيانات إعادة الجدولة غير صحيحة'); item.dueDate = dueDate; if (amount !== undefined) { if (!Number.isFinite(amount) || amount < item.paidAmount || amount <= 0) throw new Error('مبلغ إعادة الجدولة غير صحيح'); const unpaid = contract.schedule.filter((schedule) => schedule.paidAmount < schedule.amount); const outstanding = unpaid.reduce((sum, schedule) => sum + schedule.amount - schedule.paidAmount, 0); const selectedOutstanding = amount - item.paidAmount; const remaining = outstanding - selectedOutstanding; if (remaining < 0) throw new Error('مبلغ إعادة الجدولة يتجاوز الرصيد المتبقي'); item.amount = amount; const others = unpaid.filter((schedule) => schedule.id !== item.id); const base = others.length ? Math.floor(remaining / others.length) : 0; let remainder = remaining - base * others.length; for (const schedule of others) { const allocation = base + (remainder > 0 ? 1 : 0); schedule.amount = schedule.paidAmount + allocation; remainder -= remainder > 0 ? 1 : 0; } } contract.updatedAt = new Date().toISOString(); logActivity(database, 'إعادة جدولة', 'schedule', scheduleId, `إعادة جدولة القسط رقم ${item.number} للعقد ${contract.number}`); }
export function buildWhatsAppMessage(database: Database, contractId: string, scheduleId?: string, fullStatement = false) { const contract = database.contracts.find((c) => c.id === contractId); const customer = contract && database.customers.find((c) => c.id === contract.customerId); if (!contract || !customer) throw new Error('تعذر تجهيز الرسالة'); const stats = contractStats(database, contract); const template = database.settings.whatsappTemplate || whatsappTemplates[0].body; const item = scheduleId ? contract.schedule.find((s) => s.id === scheduleId) : stats.nextDue; const schedule = contract.schedule.map((s) => `${s.number}. ${dateText(s.dueDate)} — ${money(s.amount)} — مدفوع: ${money(s.paidAmount)} — متبقٍ: ${money(Math.max(0, s.amount - s.paidAmount))}`).join('\n'); const message = fullStatement ? `السلام عليكم ${customer.name}،\n\nهذا كشفكم الكامل لدى ${database.settings.shopName}:\nالمنتج: ${contract.productName}\nرقم العقد: ${contract.number}\nالمبلغ المسدد: ${money(stats.paid)}\nالمبلغ المتبقي: ${money(stats.remaining)}\nالأقساط المكتملة: ${stats.completed} من ${contract.months}\n\nجدول الأقساط:\n${schedule}\n\nشكرًا لتعاونكم.` : template.replace(/\{name\}/g, customer.name).replace(/\{shop\}/g, database.settings.shopName).replace(/\{product\}/g, contract.productName).replace(/\{contract\}/g, contract.number).replace(/\{number\}/g, String(item?.number || '')).replace(/\{months\}/g, String(contract.months)).replace(/\{date\}/g, item ? dateText(item.dueDate) : '').replace(/\{amount\}/g, item ? money(item.amount - item.paidAmount) : money(stats.remaining)); return { phone: whatsappPhone(customer.phone), message }; }
const bufferOf = (value: Uint8Array) => value.buffer.slice(value.byteOffset, value.byteOffset + value.byteLength) as ArrayBuffer;
export async function encryptBackup(database: Database, password: string) { const data = new TextEncoder().encode(JSON.stringify(database)); const salt = crypto.getRandomValues(new Uint8Array(16)); const iv = crypto.getRandomValues(new Uint8Array(12)); const keyMaterial = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveKey']); const key = await crypto.subtle.deriveKey({ name: 'PBKDF2', salt: bufferOf(salt), iterations: 100000, hash: 'SHA-256' }, keyMaterial, { name: 'AES-GCM', length: 256 }, false, ['encrypt']); const cipher = await crypto.subtle.encrypt({ name: 'AES-GCM', iv: bufferOf(iv) }, key, data); const bytes = (input: ArrayBuffer) => btoa(String.fromCharCode(...new Uint8Array(input))); return JSON.stringify({ version: 1, salt: bytes(bufferOf(salt)), iv: bytes(bufferOf(iv)), data: bytes(cipher) }); }
export async function decryptBackup(payload: string, password: string) { const parsed = JSON.parse(payload); const from = (value: string) => Uint8Array.from(atob(value), (c) => c.charCodeAt(0)); const salt = from(parsed.salt); const iv = from(parsed.iv); const keyMaterial = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveKey']); const key = await crypto.subtle.deriveKey({ name: 'PBKDF2', salt: bufferOf(salt), iterations: 100000, hash: 'SHA-256' }, keyMaterial, { name: 'AES-GCM', length: 256 }, false, ['decrypt']); const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: bufferOf(iv) }, key, bufferOf(from(parsed.data))); return JSON.parse(new TextDecoder().decode(plain)) as Database; }

export function applyDiscount(database: Database, contractId: string, scheduleId: string, amount: number, reason: string) { const contract = database.contracts.find((item) => item.id === contractId); const schedule = contract?.schedule.find((item) => item.id === scheduleId); if (!contract || !schedule || !Number.isFinite(amount) || amount <= 0 || amount > schedule.amount - schedule.paidAmount || !reason.trim()) throw new Error('بيانات الخصم غير صحيحة'); schedule.amount -= amount; contract.financedAmount -= amount; contract.totalAmount -= amount; contract.updatedAt = new Date().toISOString(); addHistory(contract, 'خصم', reason.trim()); logActivity(database, 'خصم', 'schedule', schedule.id, `خصم ${money(amount)} من القسط ${schedule.number} للعقد ${contract.number}: ${reason.trim()}`); }
export function extendContract(database: Database, contractId: string, additionalMonths: number, reason: string) { const contract = database.contracts.find((item) => item.id === contractId); if (!contract || !Number.isInteger(additionalMonths) || additionalMonths <= 0 || !reason.trim()) throw new Error('بيانات التمديد غير صحيحة'); const paidItems = contract.schedule.filter((item) => item.paidAmount >= item.amount); const unpaid = contract.schedule.filter((item) => item.paidAmount < item.amount); const outstanding = unpaid.reduce((sum, item) => sum + item.amount - item.paidAmount, 0); const total = unpaid.length + additionalMonths; const base = Math.floor(outstanding / total); let remainder = outstanding - base * total; const start = contract.schedule[contract.schedule.length - 1]?.dueDate || contract.startDate; const next = Array.from({ length: total }, (_, index) => { const date = new Date(`${start}T00:00:00`); date.setMonth(date.getMonth() + index + 1); const amount = base + (remainder > 0 ? 1 : 0); remainder -= remainder > 0 ? 1 : 0; return { id: uid('schedule'), number: paidItems.length + index + 1, dueDate: date.toISOString().slice(0, 10), amount, paidAmount: 0 }; }); contract.schedule = [...paidItems.map((item, index) => ({ ...item, number: index + 1 })), ...next]; contract.months = contract.schedule.length; contract.updatedAt = new Date().toISOString(); addHistory(contract, 'تمديد', reason); logActivity(database, 'تمديد', 'contract', contract.id, `تمديد العقد ${contract.number}: ${reason}`); }
export function cancelContract(database: Database, contractId: string, reason: string) { const contract = database.contracts.find((item) => item.id === contractId); if (!contract || !reason.trim()) throw new Error('سبب الإلغاء مطلوب'); contract.status = 'ملغى'; contract.cancellationReason = reason.trim(); contract.updatedAt = new Date().toISOString(); addHistory(contract, 'إلغاء', reason.trim()); logActivity(database, 'إلغاء', 'contract', contract.id, `إلغاء العقد ${contract.number}: ${reason.trim()}`); }
export function rescheduleContract(database: Database, contractId: string, terms: { months: number; startDate: string; reason: string }) { const contract = database.contracts.find((item) => item.id === contractId); if (!contract || !Number.isInteger(terms.months) || terms.months <= 0 || !isValidDate(terms.startDate) || !terms.reason.trim()) throw new Error('بيانات إعادة الجدولة غير صحيحة'); const paidFromSchedule = contract.schedule.reduce((sum, item) => sum + item.paidAmount, 0); const paid = Math.max(paidFor(database, contract), paidFromSchedule); const remaining = Math.max(0, contract.financedAmount - paid); contract.schedule = createSchedule(remaining, terms.months, terms.startDate).map((item) => ({ ...item, paidAmount: 0 })); contract.months = terms.months; contract.updatedAt = new Date().toISOString(); addHistory(contract, 'إعادة جدولة كاملة', terms.reason.trim()); logActivity(database, 'إعادة جدولة', 'contract', contract.id, `إعادة جدولة كاملة للعقد ${contract.number}: ${terms.reason.trim()}`); }
