import type { Database, Contract } from '../domain/types';
import { contractStats, dateText, money, statusFor } from '../domain/store';

interface Props { database: Database; contract: Contract; admin?: boolean; onPayment?: (contractId: string, scheduleId: string) => void; onWhatsApp?: (contractId: string, scheduleId?: string, full?: boolean) => void; onReschedule?: (contractId: string, scheduleId: string) => void; onReceipt?: (contractId: string, scheduleId: string) => void; onReceiptWhatsApp?: (contractId: string, scheduleId: string) => void; onPrint?: (contractId: string) => void; onEdit?: (contractId: string) => void; }

export function ContractCard({ database, contract, admin = false, onPayment, onWhatsApp, onReschedule, onReceipt, onReceiptWhatsApp, onPrint, onEdit }: Props) {
  const stats = contractStats(database, contract); const customer = database.customers.find((item) => item.id === contract.customerId); const badge = stats.overdue ? 'red' : stats.remaining ? 'orange' : 'green';
  return <article className="contract print-card"><div className="contract-top"><div><h3>{contract.productName}</h3><div className="contract-meta">العقد {contract.number} · {contract.months} أشهر · بدأ {dateText(contract.startDate)}{contract.serialNumber ? ` · الرقم التسلسلي ${contract.serialNumber}` : ''}</div>{admin && <div className="contract-meta">الزبون: {customer?.name || '—'} · {customer?.phone || '—'}</div>}</div><span className={`badge ${badge}`}>{contract.status || (stats.overdue ? 'متأخر' : stats.remaining ? 'نشط' : 'مكتمل')}</span></div><div className="progress"><i style={{ width: `${stats.percent}%` }} /></div><div className="contract-details"><span>المسدد: <b>{money(stats.paid)}</b></span><span>المتبقي: <b>{money(stats.remaining)}</b></span><span>الأشهر: <b>{stats.completed}/{contract.months}</b></span></div>{admin && <div className="row-actions contract-actions"><button className="btn muted-btn" onClick={() => onEdit?.(contract.id)}>تعديل العقد</button><button className="btn muted-btn" onClick={() => onWhatsApp?.(contract.id, undefined, true)}>كشف WhatsApp</button><button className="btn muted-btn" onClick={() => onPrint?.(contract.id)}>طباعة / PDF</button></div>}<details open={!admin} style={{ marginTop: 12 }}><summary style={{ cursor: 'pointer', color: 'var(--navy)', fontWeight: 700 }}>عرض جدول الأقساط</summary><div className="admin-table"><table><thead><tr><th>#</th><th>الاستحقاق</th><th>المبلغ</th><th>المدفوع</th><th>الحالة</th>{admin && <th>إجراء</th>}</tr></thead><tbody>{contract.schedule.map((item) => { const status = statusFor(item); return <tr key={item.id}><td>{item.number}</td><td>{dateText(item.dueDate)}</td><td>{money(item.amount)}</td><td>{money(item.paidAmount)}</td><td className={`status-${status.tone}`}>{status.label}</td>{admin && <td><div className="row-actions">{item.paidAmount < item.amount && <><button className="btn green-btn" onClick={() => onPayment?.(contract.id, item.id)}>دفعة</button><button className="btn muted-btn" onClick={() => onWhatsApp?.(contract.id, item.id)}>واتساب</button><button className="btn orange-btn" onClick={() => onReschedule?.(contract.id, item.id)}>تأجيل</button></>}{item.paidAmount > 0 && <><button className="btn muted-btn" onClick={() => onReceipt?.(contract.id, item.id)}>إيصال</button><button className="btn green-btn" onClick={() => onReceiptWhatsApp?.(contract.id, item.id)}>إرسال</button></>}</div></td>}</tr>; })}</tbody></table></div></details></article>;
}
